### ISSUE TITLE
consumerRestriction: add method support

### ISSUE THREAD

**Issue by spacewander** [mosn/htnn#253]
### Description

See https://github.com/mosn/htnn/blob/0d7c0eb0803307246d341cd244c9f94000b651c2/plugins/consumer_restriction/config.proto#L24-L26

It would be better to add a feature to limit the consumer according to the method. Like https://apisix.apache.org/docs/apisix/plugins/consumer-restriction/#restricting-by-allowed_by_methods

**Comment by hanxiantao** [comment]
plz assign this issue to me
