### ISSUE TITLE
Some basic gateway API types can be replaced by gwapiv1 instead of gwapiv1a2

### ISSUE THREAD

**Issue by spacewander** [mosn/htnn#429]
### Description

For example:
https://github.com/mosn/htnn/blob/fe0af215a43f882954de5138b0af68c84881cedf/controller/tests/benchmark/httpfilterpolicy_controller_test.go#L51

### Environment

- HTNN version:

**Comment by lyt122** [comment]
I am interested in this issue, could you assign it to me?

**Comment by lyt122** [comment]
@spacewander I found some gwapiv1b1 type also can be replaced by gwapiv1

For example: 
`var route gwapiv1b1.HTTPRoute`  can be repleced by `var route gwapiv1.HTTPRoute`

Should I replace them?

**Comment by spacewander** [comment]
The type of HTTPRoute & Gateway is intended pinned at gwapiv1b1 so their versions match the ones in istio:
https://github.com/istio/istio/blob/8f9f58bc073968436e7239bd85ac9add5d1d6f7d/pkg/config/schema/metadata.yaml#L206

**Comment by spacewander** [comment]
Would you submit the PR first to see the impact?
