### ISSUE TITLE
Change the stale bot to run once per day

### ISSUE THREAD

**Issue by spacewander** [mosn/htnn#584]
### Use Scenes

The stale bot is configured in https://github.com/mosn/htnn/blob/main/.github/workflows/stale.yml

This stale rule is from Envoy, which runs every 4 hours. We don't have many issues so running it per day is enough.

**Comment by spacewander** [comment]
@hanxiantao
Would you give it a try?

**Comment by hanxiantao** [comment]
> @hanxiantao Would you give it a try?

plz assign this issue to me
