### ISSUE TITLE
2024 OSPP sentinel plugin PR list

### ISSUE THREAD

**Issue by WeixinX** [mosn/htnn#725]
### Description

该 Issue 用于跟踪 2024 开源之夏项目【[将 Sentinel-golang 流量控制能力集成进 MoE（MOSN on Envoy) 生态](https://summer-ospp.ac.cn/org/prodetail/24f080174?list=org&navpage=org)】的开发进度
The issue is used to track the progress of the 2024 Open Source Promotion Plan project【[Integrate Sentinel-golang flow control capabilities into the MoE (MOSN on Envoy) ecosystem](https://summer-ospp.ac.cn/org/prodetail/24f080174?list=org&navpage=org)】

请按照以下 PR 顺序进行代码评审：
Please review code in the following PR order:
1. **[Deprecated]** #673 
2. **[Deprecated]** #726
3. **[Merged]** #736 
4. **[Plz Review]** #740

**Comment by spacewander** [comment]
Consider solved.
